<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Wordle</title>
    <!-- Link to your custom CSS file -->
    @vite(['resources/css/app.css'])
    <!-- Include the CSRF token for Laravel's protection -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>

<body class="bg-white/20 flex justify-center items-center min-h-screen text-white p-5 box-border">
    <div class="container bg-gray-800 p-7 rounded-2xl text-center w-full max-w-[450px] border border-white">
        <h1 class="text-xl pb-5">Simple Wordle (Laravel)</h1>
        <div id="game-board" class="grid gap-2 mb-5 w-full mx-auto grid-cols-5 grid-rows-6">
            <!-- Game board rows and letter boxes will be generated by JavaScript -->
        </div>
        <input type="text" id="guess-input" minlength="5" maxlength="5" autofocus placeholder="Type your guess..."
            class="w-full p-4 mb-5 rounded-lg bg-black text-white text-lg outline-0">
        <button id="submit-guess"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-6 rounded-lg cursor-pointer">Guess</button>
        <div id="message-area" class="mt-5 text-lg text-white font-bold">
            <!-- Messages to the user will appear here -->
        </div>
    </div>
    <!-- Link to your JavaScript file -->
    @vite(['resources/js/wordle.js'])
</body>

</html>
